name: Instalação dos softwares
author: Nome do setor
description: Instalação dos softwares requeridos por segurança da informação

# inputs:
# outputs:

runs:
  using: composite
  steps:
    - if: ${{ runner.os == "Windows" }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y \
        curl \
        net-tools \
        openssl