name: Instalação dos softwares
author: Nome do setor
description: Instalação dos softwares requeridos por segurança da informação

# inputs:
# outputs:

runs:
  using: composite
  steps:
    - shell: bash
      run: |

        echo "${{ runner.os }}"

